on:
  push:
    branches:
      - master
  schedule:
    -   cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Generate
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v2.1.5
      - name: Install Node modules
        run: |
          npm install
      - name: Generate HTML From Roam
        uses: dvargas92495/generate-roam-site-action@2.9.3
        with:
          roam_username: rodrigo@rodrigofranco.com
          roam_password: ${{ secrets.ROAM_PASSWORD }}
          roam_graph: rodrigofranco
      - name: Pull Interests and Create Calendars
        run: |
           npm install
           npm run dev
      - name: Copy includes
        run: cp -fR includes/* out/ 
      - name: Delete downloads
        run: rm -fR downloads
      - name: Generate feed
        run:  node feed; cp atom.xml out/
      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated snapshot
